const countries = [
  {
    name: 'Albania',
    topLevelDomain: [
      '.al',
    ],
    alpha2Code: 'AL',
    alpha3Code: 'ALB',
    callingCodes: [
      '355',
    ],
    capital: 'Tirana',
    altSpellings: [
      'AL',
      'Shqipëri',
      'Shqipëria',
      'Shqipnia',
    ],
    region: 'Southern Europe',
    continent: 'Europe',
    population: 2886026,
    latlng: [
      41,
      20,
    ],
    demonym: 'Albanian',
    area: 28748,
    gini: 33.2,
    timezones: [
      'UTC+01:00',
    ],
    borders: [
      'MNE',
      'GRC',
      'MKD',
      'KOS',
    ],
    nativeName: 'Shqipëria',
    numericCode: '008',
    currencies: [
      {
        code: 'ALL',
        name: 'Albanian lek',
        symbol: 'L',
      },
    ],
    languages: [
      {
        iso639_1: 'sq',
        iso639_2: 'sqi',
        name: 'Albanian',
        nativeName: 'Shqip',
      },
    ],
    translations: {
      br: 'Albânia',
      pt: 'Albânia',
      nl: 'Albanië',
      hr: 'Albanija',
      fa: 'آلبانی',
      de: 'Albanien',
      es: 'Albania',
      fr: 'Albanie',
      ja: 'アルバニア',
      it: 'Albania',
      hu: 'Albánia',
    },
    flags: [
      'https://restcountries.com/data/alb.svg',
      'https://restcountries.com/data/png/alb.png',
    ],
    regionalBlocs: [
      {
        acronym: 'CEFTA',
        name: 'Central European Free Trade Agreement',
      },
    ],
    cioc: 'ALB',
    independent: true,
  },
  {
    name: 'Andorra',
    topLevelDomain: [
      '.ad',
    ],
    alpha2Code: 'AD',
    alpha3Code: 'AND',
    callingCodes: [
      '376',
    ],
    capital: 'Andorra la Vella',
    altSpellings: [
      'AD',
      'Principality of Andorra',
      'Principat d\'Andorra',
    ],
    region: 'Southern Europe',
    continent: 'Europe',
    population: 78014,
    latlng: [
      42.5,
      1.5,
    ],
    demonym: 'Andorran',
    area: 468,
    timezones: [
      'UTC+01:00',
    ],
    borders: [
      'FRA',
      'ESP',
    ],
    nativeName: 'Andorra',
    numericCode: '020',
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'ca',
        iso639_2: 'cat',
        name: 'Catalan',
        nativeName: 'català',
      },
    ],
    translations: {
      br: 'Andorra',
      pt: 'Andorra',
      nl: 'Andorra',
      hr: 'Andora',
      fa: 'آندورا',
      de: 'Andorra',
      es: 'Andorra',
      fr: 'Andorre',
      ja: 'アンドラ',
      it: 'Andorra',
      hu: 'Andorra',
    },
    flags: [
      'https://restcountries.com/data/and.svg',
      'https://restcountries.com/data/png/and.png',
    ],
    cioc: 'AND',
    independent: true,
  },
  {
    name: 'Austria',
    topLevelDomain: [
      '.at',
    ],
    alpha2Code: 'AT',
    alpha3Code: 'AUT',
    callingCodes: [
      '43',
    ],
    capital: 'Vienna',
    altSpellings: [
      'AT',
      'Österreich',
      'Osterreich',
      'Oesterreich',
    ],
    region: 'Central Europe',
    continent: 'Europe',
    population: 8725931,
    latlng: [
      47.33333333,
      13.33333333,
    ],
    demonym: 'Austrian',
    area: 83871,
    gini: 30.8,
    timezones: [
      'UTC+01:00',
    ],
    borders: [
      'CZE',
      'DEU',
      'HUN',
      'ITA',
      'LIE',
      'SVK',
      'SVN',
      'CHE',
    ],
    nativeName: 'Österreich',
    numericCode: '040',
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
    ],
    translations: {
      br: 'Áustria',
      pt: 'Áustria',
      nl: 'Oostenrijk',
      hr: 'Austrija',
      fa: 'اتریش',
      de: 'Österreich',
      es: 'Austria',
      fr: 'Autriche',
      ja: 'オーストリア',
      it: 'Austria',
      hu: 'Ausztria',
    },
    flags: [
      'https://restcountries.com/data/aut.svg',
      'https://restcountries.com/data/png/aut.png',
    ],
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'AUT',
    independent: true,
  },
  {
    name: 'Belarus',
    topLevelDomain: [
      '.by',
    ],
    alpha2Code: 'BY',
    alpha3Code: 'BLR',
    callingCodes: [
      '375',
    ],
    capital: 'Minsk',
    altSpellings: [
      'BY',
      'Bielaruś',
      'Republic of Belarus',
      'Белоруссия',
      'Республика Беларусь',
      'Belorussiya',
      'Respublika Belarus’',
    ],
    region: 'Eastern Europe',
    continent: 'Europe',
    population: 9498700,
    latlng: [
      53,
      28,
    ],
    demonym: 'Belarusian',
    area: 207600,
    gini: 25.3,
    timezones: [
      'UTC+03:00',
    ],
    borders: [
      'LVA',
      'LTU',
      'POL',
      'RUS',
      'UKR',
    ],
    nativeName: 'Белару́сь',
    numericCode: '112',
    currencies: [
      {
        code: 'BYN',
        name: 'New Belarusian ruble',
        symbol: 'Br',
      },
      {
        code: 'BYR',
        name: 'Old Belarusian ruble',
        symbol: 'Br',
      },
    ],
    languages: [
      {
        iso639_1: 'be',
        iso639_2: 'bel',
        name: 'Belarusian',
        nativeName: 'беларуская мова',
      },
      {
        iso639_1: 'ru',
        iso639_2: 'rus',
        name: 'Russian',
        nativeName: 'Русский',
      },
    ],
    translations: {
      br: 'Bielorrússia',
      pt: 'Bielorrússia',
      nl: 'Wit-Rusland',
      hr: 'Bjelorusija',
      fa: 'بلاروس',
      de: 'Weißrussland',
      es: 'Bielorrusia',
      fr: 'Biélorussie',
      ja: 'ベラルーシ',
      it: 'Bielorussia',
      hu: 'Fehéroroszország',
    },
    flags: [
      'https://restcountries.com/data/blr.svg',
      'https://restcountries.com/data/png/blr.png',
    ],
    regionalBlocs: [
      {
        acronym: 'EEU',
        name: 'Eurasian Economic Union',
        otherAcronyms: [
          'EAEU',
        ],
      },
    ],
    cioc: 'BLR',
    independent: true,
  },
  {
    name: 'Andorra',
    topLevelDomain: [
      '.ad',
    ],
    alpha2Code: 'AD',
    alpha3Code: 'AND',
    callingCodes: [
      '376',
    ],
    capital: 'Andorra la Vella',
    altSpellings: [
      'AD',
      'Principality of Andorra',
      'Principat d\'Andorra',
    ],
    region: 'Southern Europe',
    continent: 'Europe',
    population: 78014,
    latlng: [
      42.5,
      1.5,
    ],
    demonym: 'Andorran',
    area: 468,
    timezones: [
      'UTC+01:00',
    ],
    borders: [
      'FRA',
      'ESP',
    ],
    nativeName: 'Andorra',
    numericCode: '020',
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'ca',
        iso639_2: 'cat',
        name: 'Catalan',
        nativeName: 'català',
      },
    ],
    translations: {
      br: 'Andorra',
      pt: 'Andorra',
      nl: 'Andorra',
      hr: 'Andora',
      fa: 'آندورا',
      de: 'Andorra',
      es: 'Andorra',
      fr: 'Andorre',
      ja: 'アンドラ',
      it: 'Andorra',
      hu: 'Andorra',
    },
    flags: [
      'https://restcountries.com/data/and.svg',
      'https://restcountries.com/data/png/and.png',
    ],
    cioc: 'AND',
    independent: true,
  },
  {
    name: 'Austria',
    topLevelDomain: [
      '.at',
    ],
    alpha2Code: 'AT',
    alpha3Code: 'AUT',
    callingCodes: [
      '43',
    ],
    capital: 'Vienna',
    altSpellings: [
      'AT',
      'Österreich',
      'Osterreich',
      'Oesterreich',
    ],
    region: 'Central Europe',
    continent: 'Europe',
    population: 8725931,
    latlng: [
      47.33333333,
      13.33333333,
    ],
    demonym: 'Austrian',
    area: 83871,
    gini: 30.8,
    timezones: [
      'UTC+01:00',
    ],
    borders: [
      'CZE',
      'DEU',
      'HUN',
      'ITA',
      'LIE',
      'SVK',
      'SVN',
      'CHE',
    ],
    nativeName: 'Österreich',
    numericCode: '040',
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: '€',
      },
    ],
    languages: [
      {
        iso639_1: 'de',
        iso639_2: 'deu',
        name: 'German',
        nativeName: 'Deutsch',
      },
    ],
    translations: {
      br: 'Áustria',
      pt: 'Áustria',
      nl: 'Oostenrijk',
      hr: 'Austrija',
      fa: 'اتریش',
      de: 'Österreich',
      es: 'Austria',
      fr: 'Autriche',
      ja: 'オーストリア',
      it: 'Austria',
      hu: 'Ausztria',
    },
    flags: [
      'https://restcountries.com/data/aut.svg',
      'https://restcountries.com/data/png/aut.png',
    ],
    regionalBlocs: [
      {
        acronym: 'EU',
        name: 'European Union',
      },
    ],
    cioc: 'AUT',
    independent: true,
  },
];

export default countries;
